version: '3.8'

services:
  booking-api:
    build:
      context: .
      dockerfile: Booking/Dockerfile
    container_name: booking-api
    depends_on:
      - booking-db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "8082:8082"
    networks:
      - booking-network

  booking-db:
    image: mysql:8.0
    container_name: booking-db
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: booking
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - booking-network

volumes:
  db_data:

networks:
  booking-network:
